apiVersion: v1 #string
kind: Pod #string
metadata:
  name: myapp-pod #name of the pod
  labels: #disctionary format of python
    app: myapp

spec:
  containers: #List
  image: stacksimplify/kubenginx:1.0.0
  ports:
    - containerPort: 80
      protocol: "TCP"