#kubectl apply -f pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume #it will create a volume with this name
  labels:
    type: local #this will be the label,
spec:
  storageClassName: manual
    capacity: 10G #capacity
  accessModes:
    - ReadWriteOnce #Read #ReadWriteMany
  hostPath:
    path: "/mnt/data"
