#kubectl apply -f pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume #it will create a volume with this name
  labels:
    type: local #this will be the label,
spec:
  storageClassName: manual
  capacity:
      storage: 10Gi #thin provisioing from 10Gb i am using 2Gb k8s will use only 2GB
  accessModes:
    - ReadWriteOnce //readwrietmany //read 
  hostPath:
    path: "/mnt/data"
